server:
  port: 8080

spring:
  application.name: shop
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    contexts: local


#logging.config: classpath:log4j2.yml
#logging.level:
#  org: debug
#  com.myronenko.shop.application: debug