server:
  port: 8080

spring:
  jpa.hibernate.ddl-auto: update
  application.name: shop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shop
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    contexts: local
